import React, { useState, useEffect } from 'react';
import {
  Skull,
  Activity,
  Network,
  AlertOctagon,
  Power,
  Check,
  RotateCcw,
  Volume2,
  VolumeX,
  AlertTriangle,
  Sparkles
} from 'lucide-react';
import { TaskType } from '../types';
import { generatePanicTriage, getApiKey } from '../services/gemini';

interface PanicModeViewProps {
  onAbort: () => void;
  tasks: TaskType[];
  setTasks: React.Dispatch<React.SetStateAction<TaskType[]>>;
}

export default function PanicModeView({ onAbort, tasks, setTasks }: PanicModeViewProps) {
  const defaultTask = tasks.find(t => t.status === 'critical') || tasks[0];
  const [selectedTaskId, setSelectedTaskId] = useState<string>(defaultTask?.id || '');
  const [hoursConstraint, setHoursConstraint] = useState<number>(3);
  
  const [soundOn, setSoundOn] = useState(false);
  const [sessionRunning, setSessionRunning] = useState(false);
  const [isTriageLoading, setIsTriageLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  // Lists of subtask strings generated by Gemini Panic Triage
  const [mustDoTexts, setMustDoTexts] = useState<string[]>([
    'Implement core login and route guards',
    'Write migrations for Postgres relational schemas'
  ]);
  const [skipTexts, setSkipTexts] = useState<string[]>([
    'Clean up CSS variables in landing layout',
    'Update Swagger documentation endpoints'
  ]);
  const [triageJustification, setTriageJustification] = useState<string>(
    'Survival Strategy: Focus entirely on schema integrity and login routes. Postpone all CSS styling and Swagger cleanups until first deployment is stable.'
  );

  const activeTask = tasks.find(t => t.id === selectedTaskId);
  const hasApiKey = !!getApiKey();

  // Run real Gemini API Triage
  const handleTriggerTriage = async () => {
    if (!activeTask) return;
    
    setIsTriageLoading(true);
    setErrorMessage(null);
    try {
      const subtaskStrings = activeTask.subtasks?.map(st => st.text) || [];
      const triage = await generatePanicTriage(activeTask.title, subtaskStrings, hoursConstraint);
      
      const triagedSubtasks = [
        ...triage.must_do.map(text => ({ text, completed: false })),
        ...triage.skip.map(text => ({ text, completed: true }))
      ];

      // Update Supabase if configured
      const { updateTaskSubtasks, isSupabaseConfigured } = await import('../services/supabase');
      if (isSupabaseConfigured()) {
        await updateTaskSubtasks(selectedTaskId, triagedSubtasks);
      }

      setTasks(prevTasks => prevTasks.map(t => {
        if (t.id === selectedTaskId) {
          const completedCount = triagedSubtasks.filter(st => st.completed).length;
          const progress = triagedSubtasks.length > 0 ? Math.round((completedCount / triagedSubtasks.length) * 100) : 0;
          return { ...t, subtasks: triagedSubtasks, progress };
        }
        return t;
      }));

      setMustDoTexts(triage.must_do);
      setSkipTexts(triage.skip);
      setTriageJustification(triage.justification);
    } catch (err: any) {
      setErrorMessage(err.message || 'An error occurred during Panic Mode triage.');
    } finally {
      setIsTriageLoading(false);
    }
  };

  const toggleTaskCompletion = async (taskText: string) => {
    if (!activeTask) return;
    const targetSubtaskIndex = activeTask.subtasks?.findIndex(st => st.text === taskText);
    if (targetSubtaskIndex === undefined || targetSubtaskIndex === -1) return;

    const newCompleted = !activeTask.subtasks[targetSubtaskIndex].completed;

    // Optimistic UI update
    setTasks(prevTasks => prevTasks.map(t => {
      if (t.id === selectedTaskId && t.subtasks) {
        const newSubtasks = [...t.subtasks];
        newSubtasks[targetSubtaskIndex] = {
          ...newSubtasks[targetSubtaskIndex],
          completed: newCompleted
        };
        const completedCount = newSubtasks.filter(st => st.completed).length;
        const progress = Math.round((completedCount / newSubtasks.length) * 100);
        return { ...t, subtasks: newSubtasks, progress };
      }
      return t;
    }));

    try {
      const { updateSubtaskStatus, isSupabaseConfigured } = await import('../services/supabase');
      if (isSupabaseConfigured()) {
        await updateSubtaskStatus(selectedTaskId, targetSubtaskIndex, newCompleted);
      }
    } catch (err) {
      console.error('Failed to update subtask status in Supabase:', err);
    }
  };

  return (
    <div className="relative z-10 min-h-screen flex flex-col justify-between max-w-6xl mx-auto py-10 select-none animate-in fade-in duration-500 text-on-surface">
      
      {/* Scanline atmospheric background noise effect */}
      <div className="absolute inset-0 pointer-events-none -z-10 overflow-hidden opacity-5">
        <div className="scanline"></div>
      </div>

      {/* Header status bar */}
      <header className="flex justify-between items-center mb-8 border-b border-outline/20 pb-4">
        <div className="flex items-center gap-3">
          <div className="w-3 h-3 rounded-full bg-error panic-pulse shrink-0"></div>
          <span className="font-mono text-xs font-bold text-error tracking-widest uppercase">
            Panic Mode Active
          </span>
        </div>
        <div className="flex items-center gap-6">
          <span className="font-mono text-[10px] text-on-surface-variant/80 uppercase">
            System Status: Critical
          </span>
          <button
            onClick={onAbort}
            className="font-sans text-xs font-bold text-on-surface-variant hover:text-white hover:underline cursor-pointer bg-transparent border-none flex items-center gap-1"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            <span>Abort Protocol</span>
          </button>
        </div>
      </header>

      {/* Selector and API Warning HUD */}
      <section className="grid grid-cols-1 md:grid-cols-12 gap-8 mb-6">
        <div className="md:col-span-12 space-y-4">
          {!hasApiKey && (
            <div className="bg-error/15 border border-error/30 p-4 rounded-xl flex items-center gap-3">
              <AlertTriangle className="text-error w-5 h-5 shrink-0" />
              <div className="text-xs text-on-surface-variant">
                ⚠️ Gemini API key is missing. AI Triage calls will fail. Add it in the settings configuration.
              </div>
            </div>
          )}

          <div className="glass-card p-5 rounded-2xl border border-outline/30 grid grid-cols-1 sm:grid-cols-3 gap-6 items-end bg-surface-container-low/40">
            <div>
              <label className="font-mono text-[9px] text-on-surface-variant uppercase block font-bold mb-1.5">Emergency Project</label>
              <select
                value={selectedTaskId}
                onChange={(e) => setSelectedTaskId(e.target.value)}
                className="w-full bg-surface-container border border-outline rounded-lg px-3 py-2 text-xs text-white outline-none"
              >
                {tasks.map(t => (
                  <option key={t.id} value={t.id}>{t.title} ({t.project})</option>
                ))}
              </select>
            </div>
            
            <div>
              <label className="font-mono text-[9px] text-on-surface-variant uppercase block font-bold mb-1.5">Time Remaining (Hours)</label>
              <input
                type="number"
                min="1"
                max="48"
                value={hoursConstraint}
                onChange={(e) => setHoursConstraint(parseInt(e.target.value) || 3)}
                className="w-full bg-surface-container border border-outline rounded-lg px-3 py-2 text-xs text-white outline-none"
              />
            </div>

            <button
              onClick={handleTriggerTriage}
              disabled={!hasApiKey || !selectedTaskId}
              className="py-2 px-4 bg-error text-on-error hover:brightness-110 active:scale-95 transition-all text-xs font-bold rounded-lg cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              <Sparkles className="w-4 h-4 shrink-0" />
              <span>Optimize Panic Checklist</span>
            </button>
          </div>
        </div>
      </section>

      {/* Panic Feedback Log */}
      {isTriageLoading && (
        <div className="flex flex-col items-center justify-center py-10 space-y-3">
          <Sparkles className="w-7 h-7 text-error animate-spin" />
          <p className="font-mono text-[10px] text-on-surface-variant uppercase tracking-wider">
            Re-prioritizing code bases for deadline survival...
          </p>
        </div>
      )}

      {errorMessage && (
        <div className="bg-error-container/10 border border-error/30 p-4 rounded-xl text-xs text-error font-mono mb-6">
          {errorMessage}
        </div>
      )}

      {/* Survival Strategy & Tasks Bento Block */}
      <section className="grid grid-cols-1 md:grid-cols-12 gap-8 items-stretch mb-10">
        
        {/* Survival Strategy Panel */}
        <div className="md:col-span-5 glass-card rounded-2xl p-6 flex flex-col justify-between border-error/20 panic-pulse bg-error-container/5 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-24 h-24 bg-error/5 blur-2xl -translate-y-1/2 translate-x-1/2"></div>
          <div>
            <div className="flex items-center gap-2 text-tertiary mb-4">
              <Skull className="w-5 h-5" />
              <h3 className="font-sans text-sm font-bold uppercase tracking-wider">
                AI Survival Strategy
              </h3>
            </div>
            <p className="font-sans text-sm text-on-surface leading-relaxed border-l-2 border-tertiary/40 pl-4 italic">
              "{triageJustification}"
            </p>
          </div>

          <div className="mt-8 pt-4 flex items-center justify-between border-t border-outline/20">
            <span className="font-mono text-[8px] text-on-surface-variant uppercase">
              Confidence Score: 94%
            </span>
            <div className="flex gap-1.5">
              <div className="w-1.5 h-3.5 bg-tertiary rounded-full"></div>
              <div className="w-1.5 h-3.5 bg-tertiary rounded-full"></div>
              <div className="w-1.5 h-3.5 bg-tertiary rounded-full"></div>
              <div className="w-1.5 h-3.5 bg-tertiary/20 rounded-full"></div>
            </div>
          </div>
        </div>

        {/* Must-Do Split Tasks lists */}
        <div className="md:col-span-7 glass-card rounded-2xl p-6 flex flex-col justify-between bg-surface-container/20">
          
          {/* Must-do section */}
          <div className="space-y-4">
            <div className="flex justify-between items-center border-b border-outline/20 pb-2">
              <h4 className="font-mono text-[10px] text-error font-bold tracking-widest uppercase">
                Must-Do Tasks
              </h4>
              <span className="text-error bg-error/10 border border-error/20 px-2.5 py-0.5 rounded font-mono text-[8px] font-bold">
                CRITICAL
              </span>
            </div>
            
            <ul className="space-y-2.5">
              {mustDoTexts.map((text, idx) => {
                const isCompleted = activeTask?.subtasks?.find(st => st.text === text)?.completed || false;
                return (
                  <li
                    key={idx}
                    onClick={() => toggleTaskCompletion(text)}
                    className="flex items-center gap-3 cursor-pointer select-none group"
                  >
                    <div
                      className={`w-4.5 h-4.5 rounded border-2 transition-all flex items-center justify-center shrink-0 ${
                        isCompleted
                          ? 'border-secondary bg-secondary/10'
                          : 'border-error group-hover:border-error/80'
                      }`}
                    >
                      {isCompleted && <Check className="w-3 h-3 text-secondary" />}
                    </div>
                    <span
                      className={`font-sans text-xs transition-colors ${
                        isCompleted
                          ? 'line-through text-on-surface-variant/50'
                          : 'text-on-surface group-hover:text-white'
                      }`}
                    >
                      {text}
                    </span>
                  </li>
                );
              })}
              {mustDoTexts.length === 0 && (
                <p className="text-[10px] text-on-surface-variant italic">No critical tasks detected by triage.</p>
              )}
            </ul>
          </div>

          {/* Nice-to-have deferred section */}
          <div className="space-y-4 mt-6 pt-4 border-t border-outline/20 opacity-60 hover:opacity-100 transition-opacity duration-300">
            <div className="flex justify-between items-center pb-1">
              <h4 className="font-mono text-[10px] text-on-surface-variant font-bold tracking-widest uppercase">
                Nice-to-Have Tasks
              </h4>
              <span className="text-on-surface-variant bg-surface-container px-2.5 py-0.5 rounded font-mono text-[8px] font-bold">
                DEFERRED / SKIP
              </span>
            </div>

            <ul className="space-y-2.5">
              {skipTexts.map((text, idx) => {
                const isCompleted = activeTask?.subtasks?.find(st => st.text === text)?.completed || false;
                return (
                  <li
                    key={idx}
                    onClick={() => toggleTaskCompletion(text)}
                    className="flex items-center gap-3 cursor-pointer select-none group"
                  >
                    <div
                      className={`w-4.5 h-4.5 rounded border-2 transition-all flex items-center justify-center shrink-0 ${
                        isCompleted
                          ? 'border-secondary bg-secondary/10'
                          : 'border-outline group-hover:border-outline-variant'
                      }`}
                    >
                      {isCompleted && <Check className="w-3 h-3 text-secondary" />}
                    </div>
                    <span
                      className={`font-sans text-xs transition-colors ${
                        isCompleted
                          ? 'line-through text-on-surface-variant/50'
                          : 'text-on-surface-variant group-hover:text-white'
                      }`}
                    >
                      {text}
                    </span>
                  </li>
                );
              })}
              {skipTexts.length === 0 && (
                <p className="text-[10px] text-on-surface-variant italic">No deferred tasks generated by triage.</p>
              )}
            </ul>
          </div>

        </div>
      </section>

      {/* Footer statistics gauges */}
      <footer className="grid grid-cols-1 md:grid-cols-3 gap-6 border-t border-outline/20 pt-6">
        
        {/* Stat 1 */}
        <div className="flex items-center gap-4 p-3 bg-surface-container-low/40 rounded-xl border border-outline/20">
          <div className="w-11 h-11 rounded-lg bg-surface-container flex items-center justify-center overflow-hidden relative shrink-0">
            <div className="scanline"></div>
            <Power className="text-primary w-5 h-5" />
          </div>
          <div>
            <p className="font-mono text-[9px] text-on-surface-variant uppercase tracking-wider">
              CPU LOAD
            </p>
            <p className="font-sans text-lg font-bold text-primary">82%</p>
          </div>
        </div>

        {/* Stat 2 */}
        <div className="flex items-center gap-4 p-3 bg-surface-container-low/40 rounded-xl border border-outline/20">
          <div className="w-11 h-11 rounded-lg bg-surface-container flex items-center justify-center shrink-0">
            <Network className="text-secondary w-5 h-5" />
          </div>
          <div>
            <p className="font-mono text-[9px] text-on-surface-variant uppercase tracking-wider">
              NETWORK LATENCY
            </p>
            <p className="font-sans text-lg font-bold text-secondary">14ms</p>
          </div>
        </div>

        {/* Stat 3 */}
        <div className="flex items-center gap-4 p-3 bg-surface-container-low/40 rounded-xl border border-outline/20">
          <div className="w-11 h-11 rounded-lg bg-surface-container flex items-center justify-center shrink-0">
            <AlertOctagon className="text-error w-5 h-5 animate-pulse" />
          </div>
          <div>
            <p className="font-mono text-[9px] text-on-surface-variant uppercase tracking-wider">
              ERROR RATE
            </p>
            <p className="font-sans text-lg font-bold text-error">0.02%</p>
          </div>
        </div>

      </footer>
    </div>
  );
}
